name: test
run-name: test code

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests via docker compose
        run: docker compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from tests

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose-test.yml down -v --remove-orphans

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
